# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  earlybirds_space_cdn_link: <%= ENV['EARLYBIRDS_SPACE_CDN_LINK'] %>
  cars_api_uri: <%= ENV['CARS_API_URI'] %>
  tiny_png_api_key: <%= ENV['TINY_PNG_API_KEY'] %>
  algolia_algolia_application_id: <%= ENV['ALGOLIA_APPLICATION_ID'] %>
  algolia_api_key: <%= ENV['ALGOLIA_API_KEY'] %>

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eb4e0035a94cc1fe86e23409f590557cc39275ba1d724d87249e5ea001d9d84ccae7bdbc205a5806fa2834fb455144e9365f9ebe893362e1c25951e63bfa562b

test:
  secret_key_base: 0205a0f32f5882ccc9f2ed3b699ae25375ea026894b30505617588e012a48ebf4a6153882dd50d701ba718c2fb2542600745536a7ac3e3de51cfc09913e0a6ac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
